### ISSUE TITLE
unbind_service_from_app fails with StopIteration exception

### ISSUE THREAD

**Issue by ajithmohann** [chaostoolkit/chaostoolkit-cloud-foundry#23]
I am trying to unbind a service using api method **unbind_service_from_app** which throws StopIteration exception at line 255.
It looks like **item["entity"]["name"]** returns null with V2 version of API (I have verified this explicitly) and hence not able to get bind by name.

https://github.com/chaostoolkit-incubator/chaostoolkit-cloud-foundry/blob/e6efd499b06dfecb3aec26c7d2dcc2a429ff2298/chaoscf/api.py#L255

**Comment by ajithmohann** [comment]
I later figured out that this is an issue with the set up I am using which is not setting service binding name by default. Hence closing the issue.

**Comment by rodolfocugler** [comment]
Could you please share how did you solve the issue? When I get the list of services bound to my app, the names are always null.

**Comment by ajithmohann** [comment]
The way to solve this issue is to provide a service binding name when you create the service binding.

**Comment by ajithmohann** [comment]
> Could you please share how did you solve the issue? When I get the list of services bound to my app, the names are always null.

The way to solve this issue is to provide a service binding name when you create the service binding.
