### ISSUE TITLE
Add "start app" and "stop app" actions

### ISSUE THREAD

**Issue by russmiles** [chaostoolkit/chaostoolkit-cloud-foundry#6]

**Comment by russmiles** [comment]
@singhgarima very kindly added the first half of this feature with this PR: https://github.com/chaostoolkit-incubator/chaostoolkit-cloud-foundry/pull/12

**Comment by Lawouach** [comment]
It was done in https://github.com/chaostoolkit-incubator/chaostoolkit-cloud-foundry/pull/16
